services:
  - type: web
    name: hotel-booking-api
    runtime: docker
    region: oregon
    plan: free
    branch: master
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: mysql
    healthCheckPath: /api/health
    onDeploy: |
      php artisan config:cache
      php artisan cache:clear
      php artisan permission:cache:clear
      php artisan migrate --force
      php artisan db:seed --force
